spring:
  application:
    name: CardapioHamburgueria

  datasource:
    url: jdbc:postgresql://localhost:5432/CardapioHamburgueria
    username: postgres
    password: 8190
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true



